name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: |
            uv.lock
            pyproject.toml

      - name: Install dependencies
        run: uv sync --dev --python ${{ matrix.python-version }}

      - name: Lint
        run: .venv/bin/ruff check .

      - name: Test
        run: .venv/bin/pytest -v
        env:
          WEBDAV_SERVER: all

      - name: Build
        run: uv build
